export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BY_ID';
export const GET_EMPLOYEE_BY_ID_SUCCESS = 'GET_EMPLOYEE_BY_ID_SUCCESS';
export const UPDATE_END_STATUS = 'UPDATE_END_STATUS';
export const UPDATE_END_STATUS_SUCCESS = 'UPDATE_END_STATUS_SUCCESS';

export const GET_LIST_SALARY = 'GET_LIST_SALARY';
export const GET_LIST_SALARY_SUCCESS = 'GET_LIST_SALARY_SUCCESS';
export const ADD_SALARY = 'ADD_SALARY';
export const ADD_SALARY_SUCCESS = 'ADD_SALARY_SUCCESS';
export const UPDATE_SALARY = 'UPDATE_SALARY';
export const UPDATE_SALARY_SUCCESS = 'UPDATE_SALARY_SUCCESS';
export const DELETE_SALARY = 'DELETE_SALARY';
export const DELETE_SALARY_SUCCESS = 'DELETE_SALARY_SUCCESS';

export const GET_LIST_PROMOTED = 'GET_LIST_PROMOTED';
export const GET_LIST_PROMOTED_SUCCESS = 'GET_LIST_PROMOTED_SUCCESS';
export const ADD_PROMOTED = 'ADD_PROMOTED';
export const ADD_PROMOTED_SUCCESS = 'ADD_PROMOTED_SUCCESS';
export const UPDATE_PROMOTED = 'UPDATE_PROMOTED';
export const UPDATE_PROMOTED_SUCCESS = 'UPDATE_PROMOTED_SUCCESS';
export const UPDATE_STATUS_PROMOTED = 'UPDATE_STATUS_PROMOTED';
export const UPDATE_STATUS_PROMOTED_SUCCESS = 'UPDATE_STATUS_PROMOTED_SUCCESS';
export const DELETE_PROMOTED = 'DELETE_PROMOTED';
export const DELETE_PROMOTED_SUCCESS = 'DELETE_PROMOTED_SUCCESS';

export const GET_LIST_PROPOSED = 'GET_LIST_PROPOSED';
export const GET_LIST_PROPOSED_SUCCESS = 'GET_LIST_PROPOSED_SUCCESS';
export const ADD_PROPOSED = 'ADD_PROPOSED';
export const ADD_PROPOSED_SUCCESS = 'ADD_PROPOSED_SUCCESS';
export const UPDATE_PROPOSED = 'UPDATE_PROPOSED';
export const UPDATE_PROPOSED_SUCCESS = 'UPDATE_PROPOSED_SUCCESS';
export const DELETE_PROPOSED = 'DELETE_PROPOSED';
export const DELETE_PROPOSED_SUCCESS = 'DELETE_PROPOSED_SUCCESS';
