export const GET_LIST_PENDING = 'GET_LIST_PENDING';
export const SET_LIST_PENDING = 'SET_LIST_PENDING';

export const GET_LIST_ACCEPTED = 'GET_LIST_ACCEPTED'
export const SET_LIST_ACCEPTED = 'SET_LIST_ACCEPTED'

export const GET_LIST_ACCEPTED_1 = 'GET_LIST_ACCEPTED_1'
export const SET_LIST_ACCEPTED_1 = 'SET_LIST_ACCEPTED_1'

export const GET_LIST_ACCEPTED_2 = 'GET_LIST_ACCEPTED_2'
export const SET_LIST_ACCEPTED_2 = 'SET_LIST_ACCEPTED_2'